### PR TITLE
Removes redundant characters in shortcuts

### PR DESCRIPTION
**Pull request by mutalis**
It removes redundant characters in key sequence for some shortcuts.

### CODE REVIEW

**Comment by gilesknap** [comment]
Thanks, this looks good and I can verify it still works for me with your changes.

One niggle is that the json document has totally reformatted so that it is hard to see the changes you made.

I was using the vscode json settings editor and it strangely has 4 space indents as opposed to the usual 2 used by other formatters like the redhat one - this means the file will stay in sync with the format that you get when you save it in your vscode settings.

I believe I have fixed this by:
- fixing the additional trailing commas in my main and pushing
- reformatting your document by saving it in my vscode settings and then using
  - cp /workspaces/ibek/tests/samples/schemas/quadem.ibek.ioc.schema.json .
  - (. being the git repo clone)
- pushing the above change to your branch
- rebasing your branch over my main
- force pushing the rebase to your branch

Now the differences shown in your PR if you refresh it, should be just the changes you needed to make for you keyboard compatibility.

Let me know if that is not the case and we'll fix it.

Then we can get this merged.

Cheers,
giles

**Comment by gilesknap** [comment]
Ooops - I had pushed the changes to a branch in my repo instead of your pr branch. Now that I have done that I see:

```bash
giles@ws2 work/zsa-voyager-vscode (main) » git diff pr/rdc 
```
```diff
diff --git a/keybindings.json b/keybindings.json
index fc13229..8db3e66 100644
--- a/keybindings.json
+++ b/keybindings.json
@@ -114,7 +114,7 @@
     },
     // close all other editors in group
     {
-        "key": "ctrl+shift+alt+meta+p",
+        "key": "ctrl+shift+alt+meta+P",
         "command": "workbench.action.closeOtherEditors"
     },
     // terminal resize ---------------------------------------------------------
@@ -176,11 +176,11 @@
     },
     // shift editor windows between groups
     {
-        "key": "alt+ctrl+shift+meta+o",
+        "key": "shift+alt+ctrl+shift+meta+o",
         "command": "workbench.action.moveEditorToNextGroup"
     },
     {
-        "key": "alt+ctrl+shift+meta+u",
+        "key": "shift+alt+ctrl+shift+meta+u",
         "command": "workbench.action.moveEditorToPreviousGroup"
     },
     // move between editor pages
@@ -221,7 +221,7 @@
     // rest of top row left hand:
     //  q = extensions, w = timeline, t = testing
     {
-        "key": "alt+ctrl+shift+meta+a",
+        "key": "shift+alt+ctrl+shift+meta+a",
         "command": "workbench.action.focusActivityBar"
     },
     {
@@ -239,7 +239,7 @@
     },
     {
         // scm is the key below source repositories like it is in the panel
-        "key": "alt+ctrl+shift+meta+f",
+        "key": "shift+alt+ctrl+shift+meta+f",
         "command": "workbench.view.scm"
     },
     {
```

**Comment by gilesknap** [comment]
So I'm merging. Many Thanks.

**Comment by mutalis** [comment]
@gilesknap  thanks to you.

**Pull request merged**
